name: fastcut
description: FastCut beta â€” mobile quick video editor
publish_to: "none"

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  video_player: ^2.6.0
  file_picker: ^5.2.2
  permission_handler: ^10.4.0
  ffmpeg_kit_flutter_full_gpl: ^4.5.1
  path_provider: ^2.0.11
  flutter_svg: ^2.0.6
  uuid: ^4.4.0